apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-webapp
  labels:
    app: eks-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-webapp
  template:
    metadata:
      labels:
        app: eks-webapp
    spec:
      containers:
        - name: eks-webapp
          image: 206808470236.dkr.ecr.us-east-1.amazonaws.com/eks-webapp:1.2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
